---
# system vars
ansible_python_interpreter: /usr/bin/python3

mariadb_can_restart: true

# db config
mariadb_use_official_repo: true
mariadb_use_official_repo_url: https://ftp.ubuntu-tw.org/mirror/mariadb/repo
mariadb_use_official_repo_version: 10.6

mariadb_bind_address: "0.0.0.0"

mariadb_innodb_raw: |
  innodb_buffer_pool_size = 1024M
  innodb_lock_wait_timeout = 900
  innodb_log_file_size = 64M

mariadb_databases:
  - name: "{{ slumdbd_database }}"
    state: present

mariadb_users:
  - name: "{{ slumdb_user }}"
    host: localhost
    password: "{{ slumdb_password }}"
    priv: "{{ slumdbd_database }}.*:ALL"
    state: present
