---
- name: Reload slurmdbd
  service:
    name: slurmdbd
    state: reloaded
  when: "'dbd' in slurm_roles"

- name: Restart slurmdbd
  service:
    name: slurmdbd
    state: restarted
  when: "'dbd' in slurm_roles"

- name: Reload slurmctld
  service:
    name: slurmctld
    state: reloaded
  when: "'controller' in slurm_roles"

- name: Restart slurmctld
  service:
    name: slurmctld
    state: restarted
  when: "'controller' in slurm_roles"

- name: Reload slurmd
  service:
    name: slurmd
    state: reloaded
  when: "'exec' in slurm_roles"

- name: Restart slurmd
  service:
    name: slurmd
    state: restarted
  when: "'exec' in slurm_roles"
