---
dependencies: []

galaxy_info:
  author: fauust
  role_name: mariadb
  description: MariaDB server for Debian/Ubuntu.
  license: license GPL-3.0-only
  min_ansible_version: 2.8
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - groovy
  galaxy_tags:
    - mariadb
    - mysql
